### ISSUE TITLE
All words are marked as unused

### ISSUE THREAD

**Issue by alecmev** [Zamiell/cspell-check-unused-words#2]
Seems like this command is the culprit:

https://github.com/Zamiell/cspell-check-unused-words/blob/a7652eaa46dd52a995f6fbbccef38bf977eb68d2/src/checkUnusedWords.ts#L116

Does this work for you? How? When I try to invoke `cspell` without any paths or globs it just prints help.

**Comment by Zamiell** [comment]
yeah it works for me because I use this in my cspell config: https://github.com/Zamiell/cspell-check-unused-words/blob/main/cspell.config.jsonc#L5

**Comment by Zamiell** [comment]
if you add that to your config does it work?

**Comment by alecmev** [comment]
Ah! I assumed it was something like that, and looked for this option in CSpell's docs **really** hard, and it just wasn't there 😄 Yep, adding this helps, and also something I wanted to have regardless, thanks!

**Comment by Zamiell** [comment]
i guess its a bug in the checker though since it should handle that case

**Comment by Zamiell** [comment]
fixed by this commit: https://github.com/complete-ts/cspell-check-unused-words/commit/b30640fb3e4b7a8e8501a99adef9a3d3dfd4b6f7
