### ISSUE TITLE
Temporary config should be in some git-ignored directory or in `os.tmpdir()`

### ISSUE THREAD

**Issue by alecmev** [Zamiell/cspell-check-unused-words#3]
I run this in parallel with other checks, and some of them, e.g., Prettier, sometimes pick up on the temporary file. I'll add `npm-debug.log.cspell.config.json` to `.gitignore` for now, but it would be nice to not have that. `os.tmpdir()` is preferable because some tools, like ESLint, don't respect `.gitignore` by default.

**Comment by Zamiell** [comment]
> npm-debug.log.cspell.config.json

you shouldn't have to because it is in [the gitignore file](https://github.com/github/gitignore/blob/main/Node.gitignore#L4) by default

**Comment by alecmev** [comment]
Hmm, but these are third-party templates, not Git defaults. We don't have `npm-debug.log*` in our `.gitignore` because we use Yarn, which generates a different error log file.

**Comment by Zamiell** [comment]
I'll try using os.tmpdir, it is a better solution

**Comment by alecmev** [comment]
Thank you! [`mkdtemp`](https://nodejs.org/api/fs.html#fspromisesmkdtempprefix-options) is probably the way to go.

**Comment by Zamiell** [comment]
do I need to use that? see this commit: https://github.com/Zamiell/cspell-check-unused-words/commit/21a65cbcd5d1cb54c641d5a3be7e0c4703b15a87

**Comment by Zamiell** [comment]
i published v1.3.4 with these two fixes:
- https://github.com/Zamiell/cspell-check-unused-words/commit/b30640fb3e4b7a8e8501a99adef9a3d3dfd4b6f7
- https://github.com/Zamiell/cspell-check-unused-words/commit/21a65cbcd5d1cb54c641d5a3be7e0c4703b15a87

**Comment by alecmev** [comment]
Ah! That was very fast, thank you 😉 Collision is possible, but seems unlikely, given the lifetime of only a few seconds. It might cause problems with tests though, if there will be any in the future.

**Comment by Zamiell** [comment]
oh, then i'll rename the file based on the name of the CWD/project then

**Comment by alecmev** [comment]
Or a random string? 100% future-proof 😛

**Comment by Zamiell** [comment]
ok, i'll do project name + random string suffix then

**Comment by Zamiell** [comment]
https://github.com/complete-ts/cspell-check-unused-words/commit/3cc404355dfbce964c5db501e01c3d189c24ba3f

**Comment by alecmev** [comment]
Awesome, thanks again! 👍

**Comment by Zamiell** [comment]
turns out having it be in a temp config causes other problems, so I had to revert this behavior.
for more info see: https://github.com/streetsidesoftware/cspell/issues/6262

**Comment by alecmev** [comment]
That's a shame, but thank you for context! This is starting to look like a huge job, just for sake of saving a line in a couple of ignore files 😄 Not worth so much effort, but I suppose the ball is in CSpell's court now.
